import Head from "next/head";
import Image from "next/image";
import React, { useState, useEffect } from "react";
import Banner from "../components/banner/Banner";
import Headers from "../components/headers/Headers";
import Header_category from "../components/Header_category/Header_category";

export default function Home() {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 3000);
  }, []);

  return (
    <div className="feature-font">
      <Head>
        <title>Kart Bazar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        ></link>
      </Head>

      <header>
        <div>
          <Headers />
          <Banner />
          <Header_category />
        </div>
      </header>
      {loading && (
        <div
          style={{ minHeight: "90vh" }}
          className="flex items-center justify-center"
        >
          <span className="main-loader"></span>
        </div>
      )}
      {!loading && <main></main>}
      <footer>{/* <Headers/> */}</footer>
    </div>
  );
}
