import Head from 'next/head'
import Image from 'next/image'
import React, { useState, useEffect } from "react";
import Headers from '../components/headers/Headers';

export default function Home() {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 3000);
  }, []);

  
  return (
    <div className="feature-font">
    <Head>
      <title>Kart Bazar</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <header>
      <div>
  
       <Headers/>
      </div>
    </header>
    {loading && (
      <div
        style={{ minHeight: "90vh" }}
        className="flex items-center justify-center"
      >
        <span className="main-loader"></span>
      </div>
    )}
    {!loading && (
      <main>
       
      </main>
    )}
    <footer>
    {/* <Headers/> */}
    </footer>
  </div>
  )
}
